plot(e3(1,:),DEAPTH,'-b',...
     e1(1,:),DEAPTH,'-g',...     
     e2(1,:),DEAPTH,'-r',...
     e3(2,:),DEAPTH,'--b',...
     e1(2,:),DEAPTH,'--g',...
     e2(2,:),DEAPTH,'--r',...
     e3(8,:),DEAPTH,'-.b',...
     e1(8,:),DEAPTH,'-.g',...
     e2(8,:),DEAPTH,'-.r',...
     TAYLOR(:,3),TAYLOR(:,1),'ob',...
     TAYLOR(:,4),TAYLOR(:,1),'og',...
     TAYLOR(:,5),TAYLOR(:,1),'or',...
     'LineWidth',3);
set(gca,'YDir','reverse','FontSize',14, 'FontWeight','bold')
xlabel('Eigenvalue')
ylabel('Depth (m)')
legend('E_z : No NNI','E_y','E_x','E_z : mild NNI','E_y','E_x','E_z : full NNI','E_y','E_x','S_z: ice core','S_y','S_x')

%% NO NNI -- climate signal
plot(e3(1,:,1),DEAPTH,'-c',...
     e3(2,:,1),DEAPTH,'-m',...
     e3(3,:,1),DEAPTH,'-k',...
     e1(1,:,1),DEAPTH,'--c',...
     e1(2,:,1),DEAPTH,'--m',...
     e1(3,:,1),DEAPTH,'--k',...
     e2(1,:,1),DEAPTH,'-dc',...
     e2(2,:,1),DEAPTH,'-dm',...
     e2(3,:,1),DEAPTH,'-dk',...
     'LineWidth',4,'MarkerSize',6);
set(gca,'YDir','reverse','FontSize',14, 'FontWeight','bold')
xlabel('Eigenvalue')
ylabel('Depth (m)')
legend('E_z','','','E_y','','','E_x','','');
axis([0,.9,50,400])

%% MILD NNI
plot(e3(1,:,2),DEAPTH,'-c',...
     e3(2,:,2),DEAPTH,'-m',...
     e3(3,:,2),DEAPTH,'-k',...
     e1(1,:,2),DEAPTH,'--c',...
     e1(2,:,2),DEAPTH,'--m',...
     e1(3,:,2),DEAPTH,'--k',...
     e2(1,:,2),DEAPTH,'-dc',...
     e2(2,:,2),DEAPTH,'-dm',...
     e2(3,:,2),DEAPTH,'-dk',...
     'LineWidth',4,'MarkerSize',6);
set(gca,'YDir','reverse','FontSize',14, 'FontWeight','bold')
xlabel('Eigenvalue')
ylabel('Depth (m)')
legend('E_z','','','E_y','','','E_x','','');
axis([0,.9,50,400])


%% FULL NNI
plot(e3(1,:,8),DEAPTH,'-c',...
     e3(2,:,8),DEAPTH,'-m',...
     e3(3,:,8),DEAPTH,'-k',...
     e1(1,:,8),DEAPTH,'--c',...
     e1(2,:,8),DEAPTH,'--m',...
     e1(3,:,8),DEAPTH,'--k',...
     e2(1,:,8),DEAPTH,'-dc',...
     e2(2,:,8),DEAPTH,'-dm',...
     e2(3,:,8),DEAPTH,'-dk',...
     'LineWidth',4,'MarkerSize',6);
set(gca,'YDir','reverse','FontSize',14, 'FontWeight','bold')
xlabel('Eigenvalue')
ylabel('Depth (m)')
legend('E_z','','','E_y','','','E_x','','');
axis([0,.9,50,400])


%% delta eigen

plot((e3(2,:,1)-(e3(1,:,1)+e3(3,:,1))/2),DEAPTH,'-b',...
     (e3(2,:,2)-(e3(1,:,2)+e3(3,:,2))/2),DEAPTH,'-r',...
     (e3(2,:,8)-(e3(1,:,8)+e3(3,:,8))/2),DEAPTH,'-g',...
     'LineWidth',4,'MarkerSize',6);
set(gca,'YDir','reverse','FontSize',14, 'FontWeight','bold')
xlabel('\Delta E_z')
ylabel('Depth (m)')
legend('No NNI','mild NNI','full NNI')
axis([0.04,.09,50,400])

%% stress

plot(squeeze(stress(3,3,:)),depth,'-b',...
         squeeze(stress(2,2,:)),depth,'-r',...
         squeeze(stress(1,1,:)),depth,'--g',...
         'LineWidth',4,'MarkerSize',6);
set(gca,'YDir','reverse','FontSize',20, 'FontWeight','bold')
ylabel('Depth (m)')
xlabel('Deviatoric Stress (Pa)')
legend('S_{33}','S_{22}','S_{11}','Location','North')