plot(e3(1,:),DEAPTH,'-b',...
     e1(1,:),DEAPTH,'-g',...     
     e2(1,:),DEAPTH,'-r',...
     e3(2,:),DEAPTH,'--b',...
     e1(2,:),DEAPTH,'--g',...
     e2(2,:),DEAPTH,'--r',...
     e3(8,:),DEAPTH,'-.b',...
     e1(8,:),DEAPTH,'-.g',...
     e2(8,:),DEAPTH,'-.r',...
     TAYLOR(:,3),TAYLOR(:,1),'ob',...
     TAYLOR(:,4),TAYLOR(:,1),'og',...
     TAYLOR(:,5),TAYLOR(:,1),'or',...
     'LineWidth',3);
set(gca,'YDir','reverse','FontSize',14, 'FontWeight','bold')
xlabel('Eigenvalue')
ylabel('Depth (m)')
legend('E_z : No NNI','E_y','E_x','E_z : mild NNI','E_y','E_x','E_z : full NNI','E_y','E_x','S_z: ice core','S_y','S_x')

%%

plot(e3(1,:,8),DEAPTH,'-g',...
     e3(2,:,8),DEAPTH,'-b',...
     e3(3,:,8),DEAPTH,'-r',...
     e1(1,:,8),DEAPTH,'--g',...
     e1(2,:,8),DEAPTH,'--b',...
     e1(3,:,8),DEAPTH,'--r',...
     e2(1,:,8),DEAPTH,'-dg',...
     e2(2,:,8),DEAPTH,'-db',...
     e2(3,:,8),DEAPTH,'-dr',...
     'LineWidth',4,'MarkerSize',6);
set(gca,'YDir','reverse','FontSize',14, 'FontWeight','bold')
xlabel('Eigenvalue')
ylabel('Depth (m)')
legend('E_z','','','E_y','','','E_x','','');
