%% taylorNNI_watson.eps
plot(squeeze(eig(1,:,1)),DEAPTH,'-b',...
     squeeze(eig(2,:,1)),DEAPTH,'-g',...     
     squeeze(eig(3,:,1)),DEAPTH,'-r',...
     squeeze(eig(1,:,2)),DEAPTH,'--b',...
     squeeze(eig(2,:,2)),DEAPTH,'--g',...
     squeeze(eig(3,:,2)),DEAPTH,'--r',...
     squeeze(eig(1,:,5)),DEAPTH,'-.b',...
     squeeze(eig(2,:,5)),DEAPTH,'-.g',...
     squeeze(eig(3,:,5)),DEAPTH,'-.r',...
     TAYLOR(:,3),TAYLOR(:,1),'ob',...
     TAYLOR(:,4),TAYLOR(:,1),'or',...
     TAYLOR(:,5),TAYLOR(:,1),'og',...
     'LineWidth',3);
set(gca,'YDir','reverse','FontSize',24, 'FontWeight','bold')
xlabel('Eigenvalue')
ylabel('Depth (m)')
legend('E_1 : No NNI','E_2','E_3','E_1 : mild NNI','E_2','E_3','E_1 : full NNI','E_2','E_3','E_1 : ice core','E_2','E_3')

%% taylorNNI_uniCone.eps
plot(squeeze(eig(1,:,6)),DEAPTH,'-b',...
     squeeze(eig(2,:,6)),DEAPTH,'-g',...     
     squeeze(eig(3,:,6)),DEAPTH,'-r',...
     squeeze(eig(1,:,7)),DEAPTH,'--b',...
     squeeze(eig(2,:,7)),DEAPTH,'--g',...
     squeeze(eig(3,:,7)),DEAPTH,'--r',...
     squeeze(eig(1,:,8)),DEAPTH,'-.b',...
     squeeze(eig(2,:,8)),DEAPTH,'-.g',...
     squeeze(eig(3,:,8)),DEAPTH,'-.r',...
     TAYLOR(:,3),TAYLOR(:,1),'ob',...
     TAYLOR(:,4),TAYLOR(:,1),'og',...
     TAYLOR(:,5),TAYLOR(:,1),'or',...
     'LineWidth',3);
set(gca,'YDir','reverse','FontSize',24, 'FontWeight','bold')
xlabel('Eigenvalue')
ylabel('Depth (m)')
legend('E_1 : No NNI','E_2','E_3','E_1 : mild NNI','E_2','E_3','E_1 : full NNI','E_2','E_3','E_1 : ice core','E_2','E_3')

%% fabric

run = 1;
stp = 2100;
elm = 1;

cdist = load([dir,'/Run',num2str(run),'/Step',num2str(stp,'%05.0f'),'_EL',num2str(elm,'%09.0f'),'.mat']);

equalAreaPoint([cdist.theta, cdist.phi])

%% Taylor depth stress

load +Taylor/devstress.mat
plot(d11r(400:200:end)/100000,z(400:200:end),'-vk',...
     d22r(400:200:end)/100000,z(400:200:end),'-^k',...
     d33r(400:200:end)/100000,z(400:200:end),'-xk',...
     d11d(400:200:end)/100000,z(400:200:end),'-sk',...
     d22d(400:200:end)/100000,z(400:200:end),'-+k',...
     d33d(400:200:end)/100000,z(400:200:end),'-ok',...
'LineWidth',3,'MarkerSize',18)

set(gca,'YDir','reverse','FontSize',24, 'FontWeight','bold')
xlabel('Deviatoric Stress (Bar)')
ylabel('Depth (m)')
% legend('\sigma_{11}^{ridge}','\sigma_{22}^{ridge}','\sigma_{33}^{ridge}','\sigma_{11}^{dome}','\sigma_{22}^{dome}','\sigma_{33}^{dome}')
legend('XX, Ridge','YY','ZZ','XX, Dome','YY','ZZ')
