function structure
%   structure is a gui used to build the initial structure for the Thor model. 
%
%
%
%

% initialize and hide the GUI as it is being created
f = figure('Visible','off','Position',[200,200,800,380]);

% create Model-wide Components panel
HComp1 = uipanel('Title', 'Model-wide Components','FontSize',12,...
                 'BackgroundColor', [0.7, 0.7, 0.7], 'Units', 'pixels',...
                 'Position', [10, 10, 430, 85]);%#ok<NASGU>

% create Element-wide Components panel
HComp2 = uipanel('Title', 'Element-wide Components','FontSize',12,...
                 'BackgroundColor', [0.7, 0.7, 0.7], 'Units', 'pixels',...
                 'Position', [10, 80, 430, 200]);%#ok<NASGU>
             
% create Crystal Distrobution Components panel
HComp3 = uipanel('Title', 'Crystal Distrobution Components','FontSize',12,...
                 'BackgroundColor', [0.7, 0.7, 0.7], 'Units', 'pixels',...
                 'Position', [10, 265, 430, 105]);%#ok<NASGU>

% create Explination panel
% HComp4 = uipanel('Title', 'Directions','FontSize',12,...
%                  'BackgroundColor', [0.7, 0.7, 0.7], 'Units', 'pixels',...
%                  'Position', [450, 10, 340, 360]);
             
% Creat the explination
Hexpl = uicontrol('Style', 'edit','HorizontalAlignment','left','Max',2,'Min',0,...
                  'String',{...
'In the Crystal Distrobution Components: Select the Crystal Distrobution Components you desire for your model.',...
' ',...
'In the Element-wide Components: Enter the number of elements to create for your model. Edit the inbuild structure feilds: disangles, glenexp, stress, grain, and T. Once a feild is set how you want it, check the check-box for the corrosponding variable. You will not be able to build the initial setting structure until they are all checked.',...
' ',...
'    Distrobution Angle Variable (inbuild.disangles): #ELEMENTSx2 array holding [Ao1, A1; ...; Ao_NELEM, A_NELEM] where the `Ao`s are the girdle angle of the crystal distrobution and the `A`s are the cone angles of the distrobution.',...
' ',...
'    Glen Exponent Variable (inbuild.glenexp): #ELEMENTSx1 array holding the exponent from glens flow law for each element. 3 is generaly used for all elements.',...
' ',...
'     Stress Tensor Variable (inbuild.stress): 3x3x#ELEMENTS array holding the stress tensor for each element.',...
' ',...
'     Max/Min Grain Size Variable (inbuild.grain): #ELEMENTSx2 array holding, [MIN, MAX], the minimum, MIN, and maximum, MAX, crystal diameters for building a crystal distrobution. Grain sizes are picked randomly from within this open interval.',...
' ',...
'     Tempurature variable(inbuild.T): #ELEMENTSx1 array holding the temperature of each element.',...
' ',...
'In the model-wide Components: Turn on or off Nearest Neigbor Interaction (NNI) then enter the strength of the neighboring crystal relative to the center crystal. Next, Enter then time step size and select the appropriate units.'},...
                  'Position',[450,10,340,360]);%#ok<NASGU>
             
% Construct the Crystal Distrobution components

    % Number of crystals
    Hnumbcrys    = uicontrol('Style','popupmenu',...
                             'String',{'125','216','512','1000','1728',...
                                       '2744','4096','5832','8000','10648','15625'},...
                             'Position',[90,280,70,30]);
         Htext1  = uicontrol('Style','text','String',...
                             'Number of Crystals',...
                             'Position',[90,315,70,30]); %#ok<NASGU>

    % Conectivity structure type                     
    Hcontype    = uicontrol('Style', 'popupmenu',...
                            'String', {'Cubic','Hexagonal'},...
                            'Position', [180,280,80,30]);
         Htext2  = uicontrol('Style','text','String',...
                             'Conectivity Structure',...
                             'Position',[180,315,80,30]); %#ok<NASGU>

    % Distrobution type
    Hdistype    = uicontrol('Style', 'popupmenu',...
                            'String', 'Isotropic',...
                            'Position', [280,280,80,30]);
         Htext3  = uicontrol('Style','text','String',...
                             'Distrobution Type',...
                             'Position',[280,315,80,30]);%#ok<NASGU>
    


% Construct the Element wide components

    % Distrobution angles
    Hconangle    = uicontrol('Style', 'checkbox',...
                            'Position', [220-10,190,20,30]);
         Htext4  = uicontrol('Style','text','String',...
                             'Distrobution Angle Variable',...
                             'Position',[160,225,120,30]);%#ok<NASGU>

    % Number of elements
    Hnelem       = uicontrol('Style', 'edit',...
                            'Position', [20,190,120,30]);
         Htext5  = uicontrol('Style','text','String',...
                             'Number of Elements',...
                             'Position',[20,225,120,30]);%#ok<NASGU>
                         
    % Glen Exponent
    Hglenexp     = uicontrol('Style', 'checkbox',...
                            'Position', [360-10,190,20,30]);
         Htext6  = uicontrol('Style','text','String',...
                             'Glen Exponent Variable',...
                             'Position',[300,225,120,30]);%#ok<NASGU>

    % Stress tensors
    Hstress      = uicontrol('Style', 'checkbox',...
                            'Position', [80-10,110,20,30]);
         Htext7  = uicontrol('Style','text','String',...
                             'Stress Tensor Variable',...
                             'Position',[20,145,120,30]);%#ok<NASGU>
                         
    % Grain size (min, max)
    Hgrain       = uicontrol('Style', 'checkbox',...
                            'Position', [220-10,110,20,30]);
         Htext8  = uicontrol('Style','text','String',...
                             'Max/Min Grain Size Variable',...
                             'Position',[160,145,120,30]);%#ok<NASGU>

    % Temperature Variable Name
    Hstress      = uicontrol('Style', 'checkbox',...
                            'Position', [360-10,110,20,30]);
         Htext11  = uicontrol('Style','text','String',...
                             'Tempurature Variable',...
                             'Position',[300,145,120,30]);%#ok<NASGU>
                         

                         
% Construct the model wide components


    % Time Step Size
    Hconangle    = uicontrol('Style', 'edit',...
                            'Position', [160,20,120,30]);
         Htext9  = uicontrol('Style','text','String',...
                             'Time Step Size',...
                             'Position',[160,55,120,15]);%#ok<NASGU>

    % Time Step Units
    Hglenexp     = uicontrol('Style','popupmenu',...
                            'String', {'Seconds','Days', 'Weeks', 'Monthes', 'Years'},...
                            'Position', [300,15,120,30]);
         Htext10  = uicontrol('Style','text','String',...
                             'Time Step Units',...
                             'Position',[300,55,120,15]);%#ok<NASGU>
    
    % On Off Nearest Neigbor Interaction
    Hynsoft     = uicontrol('Style', 'checkbox',...
                            'Position', [30,25,20,20]);
         Htext12  = uicontrol('Style','text','String',...
                             'NNI',...
                             'Position',[20,55,40,15]);%#ok<NASGU>
                         
    % Time Step Size
    Hsoft       = uicontrol('Style', 'edit',...
                            'Position', [70,20,70,30]);
         Htext13  = uicontrol('Style','text','String',...
                             'NNI Size',...
                             'Position',[70,55,70,15]);%#ok<NASGU>


set(f,'Visible','on')




end