function structure
%   structure is a gui used to build the initial structure for the Thor model. 
%
%
%
%

% initialize and hide the GUI as it is being created
f = figure('Visible','off','Position',[200,200,800,600]);

% Construct the Crystal Distrobution components

    % Number of crystals
    Hnumbcrys    = uicontrol('Style','popupmenu',...
                             'String',{'125','216','512','1000','1728',...
                                       '2744','4096','5832','8000','10648','15625'},...
                             'Position',[20,320,70,30]);
         Htext1  = uicontrol('Style','text','String',...
                             'Number of Crystals',...
                             'Position',[20,355,70,30]);

    % Conectivity structure type                     
    Hcontype    = uicontrol('Style', 'popupmenu',...
                            'String', {'Cubic','Hexagonal'},...
                            'Position', [110,320,80,30]);
         Htext2  = uicontrol('Style','text','String',...
                             'Conectivity Structure',...
                             'Position',[110,355,80,30]);

    % Distrobution type
    Hdistype    = uicontrol('Style', 'popupmenu',...
                            'String', 'Isotropic',...
                            'Position', [210,320,80,30]);
         Htext3  = uicontrol('Style','text','String',...
                             'Distrobution Type',...
                             'Position',[210,355,80,30]);
    


% Construct the Element wide components

    % Distrobution angles
    Hconangle    = uicontrol('Style', 'edit',...
                            'Position', [160,220,120,30]);
         Htext4  = uicontrol('Style','text','String',...
                             'Distrobution Angle Variable',...
                             'Position',[160,255,120,30]);

    % Number of elements
    Hnelem       = uicontrol('Style', 'edit',...
                            'Position', [40,220,80,30]);
         Htext5  = uicontrol('Style','text','String',...
                             'Number of Elements',...
                             'Position',[40,255,80,30]);
                         
    % Glen Exponent
    Hglenexp     = uicontrol('Style', 'edit',...
                            'Position', [300,220,120,30]);
         Htext6  = uicontrol('Style','text','String',...
                             'Glen Exponent Variable',...
                             'Position',[300,255,120,30]);

    % Stress tensors
    Hstress      = uicontrol('Style', 'edit',...
                            'Position', [20,120,120,30]);
         Htext7  = uicontrol('Style','text','String',...
                             'Stress Tensor Variable',...
                             'Position',[20,155,120,30]);
                         
    % Grain size (min, max)
    Hgrain       = uicontrol('Style', 'edit',...
                            'Position', [160,120,120,30]);
         Htext8  = uicontrol('Style','text','String',...
                             'Max/Min Grain Size Variable',...
                             'Position',[160,155,120,30]);

    % Temperature Variable Name
    Hstress      = uicontrol('Style', 'edit',...
                            'Position', [300,120,120,30]);
         Htext11  = uicontrol('Style','text','String',...
                             'Tempurature Variable',...
                             'Position',[300,155,120,30]);
                         

                         
% Construct the model wide components


    % Time Step Size
    Hconangle    = uicontrol('Style', 'edit',...
                            'Position', [160,20,120,30]);
         Htext9  = uicontrol('Style','text','String',...
                             'Time Step Size',...
                             'Position',[160,55,120,15]);

    % Time Step Units
    Hglenexp     = uicontrol('Style','popupmenu',...
                            'String', {'Seconds','Days', 'Weeks', 'Monthes', 'Years'},...
                            'Position', [300,15,120,30]);
         Htext10  = uicontrol('Style','text','String',...
                             'Time Step Units',...
                             'Position',[300,55,120,15]);
    
    % On Off Nearest Neigbor Interaction
    Hynsoft     = uicontrol('Style', 'checkbox',...
                            'Position', [30,25,20,20]);
         Htext12  = uicontrol('Style','text','String',...
                             'NNI',...
                             'Position',[20,55,40,15]);
                         
    % Time Step Size
    Hsoft       = uicontrol('Style', 'edit',...
                            'Position', [70,20,70,30]);
         Htext13  = uicontrol('Style','text','String',...
                             'NNI Size',...
                             'Position',[70,55,70,15]);


set(f,'Visible','on')




end